# https://github.com/drduh/YubiKey-Guide/blob/main/config/dirmngr.conf
# https://www.gnupg.org/documentation/manuals/gnupg/Dirmngr-Options.html

# Keyserver URL
#keyserver hkps://keys.openpgp.org
#keyserver hkps://keys.mailvelope.com
#keyserver hkps://keyserver.ubuntu.com:443
#keyserver hkps://pgpkeys.eu
#keyserver hkps://pgp.circl.lu
#keyserver hkp://zkaan2xfbuxia2wpf7ofnkbz6r5zdbbvxbunvp5g2iebopbfc4iqmbad.onion
