# https://github.com/drduh/YubiKey-Guide/blob/main/config/gpg-agent.conf
# https://www.gnupg.org/documentation/manuals/gnupg/Agent-Options.html

# Set SSH_AUTH_SOCK to replace ssh-agent with gpg-agent
enable-ssh-support

# Seconds to cache entry, reset with each access
# Default: 600 seconds (10 minutes)
default-cache-ttl 60

# Maximum seconds to cache entry
# Default: 7200 seconds (2 hours)
max-cache-ttl 300

# Terminal device for pinentry
#ttyname $GPG_TTY

# Pinentry prompt duration
# Default: 0
#pinentry-timeout 30

# Select a valid pinentry program path below

# Linux
# Default: /usr/bin/pinentry
#pinentry-program /usr/bin/pinentry
#pinentry-program /usr/bin/pinentry-curses
#pinentry-program /usr/bin/pinentry-gnome3
#pinentry-program /usr/bin/pinentry-tty
#pinentry-program /usr/bin/pinentry-x11

# macOS (Apple silicon)
# Default: /opt/homebrew/bin/pinentry
#pinentry-program /opt/homebrew/bin/pinentry
#pinentry-program /opt/homebrew/bin/pinentry-curses
#pinentry-program /opt/homebrew/bin/pinentry-mac
#pinentry-program /opt/homebrew/bin/pinentry-tty

# macOS (Intel)
# Default: /usr/local/bin/pinentry
#pinentry-program /usr/local/bin/pinentry
#pinentry-program /usr/local/bin/pinentry-curses
#pinentry-program /usr/local/bin/pinentry-mac
#pinentry-program /usr/local/bin/pinentry-tty

# macOS (MacPorts)
#pinentry-program /opt/local/bin/pinentry

# macOS (MacGPG2)
#pinentry-program /usr/local/MacGPG2/libexec/pinentry-mac.app/Contents/MacOS/pinentry-mac

# Windows (https://developers.yubico.com/PGP/SSH_authentication/Windows.html)
#enable-win32-openssh-support
