# https://github.com/drduh/YubiKey-Guide/blob/main/config/scdaemon.conf
# https://www.gnupg.org/documentation/manuals/gnupg/Scdaemon-Options.html

# Disable PIV application (prioritize GPG)
disable-application piv

# Disable CCID driver support (use PC/SC)
disable-ccid

# Extra information
#verbose

# Debug level: none, basic, advanced, expert, guru.
#debug-level basic

# List with: gpg-connect-agent 'scd getinfo app_list' /bye
#application-priority openpgp,piv

# Limit access to admin command
#deny-admin
