# https://github.com/drduh/YubiKey-Guide/blob/main/config/scdaemon.conf
# https://www.gnupg.org/documentation/manuals/gnupg/Scdaemon-Options.html
# Disable PIV application (prioritize GPG)
disable-application piv
# Disable CCID driver support (use PC/SC)
disable-ccid
